### PR TITLE
user-enabled sha-inv should never report to swabber

### PR DESCRIPTION
**Pull request by joelanders**

### CODE REVIEW

**Comment by tomryanx** [comment]
This doesn't LGTM... I can see that something *like* this would work, but it's a bit hacky.

Some thoughts:
* this will prevent us from implementing "sysops" challenges, because it will be overridden by the user setting
* has attention been given to whether having up to `N` hits before banning could cause memory issues in banjax and/or other perf issues?
* i could go either way on whether we use a new clients.yml var or reuse the existing one, but if we have a new one the logic should be: if sysops enabled, enable normally and done. if not sysops enabled, then if user-enabled enable without banning then done. Or if enabled, then if sysops-enabled enable normally fi, if user-enabled enable without banning, fi fi. Or something like that.
* Not *totally* related to this PR, but I would like to be sure that dashboard correctly reports when a user enables challenger, as opposed to a "sudo as user" administrator

And most of all:
* imo we should be modifying banjax itself to make this logic work. Much cleaner. And gotta make sure sysops-enabled clobbers user-enabled, not the other way around.

**Comment by tomryanx** [comment]
Assuming `no_of_fails_to_ban: 0` works as intended, this LGTM

**Comment by joelanders** [comment]
So I amended this to make the sysops-enabled sha-inv shallenger take priority over a user-enabled one.

Re: memory usage in banjax:
```
      // How much failure are we going to tolerate 0 means infinite tolerance
      if (ch["no_of_fails_to_ban"]) {
        host_challenge_spec->fail_tolerance_threshold = ch["no_of_fails_to_ban"].as<unsigned int>();
      }
```
so I think we can assume a value of 0 achieves our desired effect in a way intended by the banjax authors (ie. without being hacky).

I haven't taken into account any "sudo as user" differences, I'll ask vladimir what's least surprising for him today.

**Comment by RamJett** [comment]
This already got implemented in v1 and today in v1.5

**Pull request closed without merging**
